## Initial copy taken from: https://github.ibm.com/one-pipeline/hello-compliance-app/blob/master/.pipeline-config.yaml

version: '1'
setup: #code-setup
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.25@sha256:dd2000b525336acd00e9b95b74f15696797764725adbb25fa720e9431d558cbf
  script: |
    #!/usr/bin/env bash
    chmod +x $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/one-pipeline/scripts/*.sh
    . $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/one-pipeline/scripts/code-setup.sh
    exit $?

detect-secrets: # Detect-secrets (Normally defaults but no-op for now as liberty found 21633 potential secrets that need auditing)
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.25
  dind: true
  abort_on_failure: stopAndFail
  script: |
    #!/bin/sh
    echo "Detect Secrets has been disabled for OpenLiberty Prototyping due to large number of unaudited potential secrets"
    # "/opt/commons/detect-secrets/run_scan.sh"    
test:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.25@sha256:dd2000b525336acd00e9b95b74f15696797764725adbb25fa720e9431d558cbf
  script: |
    #!/usr/bin/env bash
    . $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/one-pipeline/scripts/unit-test.sh
    exit $?

compliance-checks:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.25
  dind: true
  abort_on_failure: false
  script: |
    #!/bin/sh
    echo "compliance-checks Code goes here"
    # "/opt/commons/compliance-checks/run.sh"        
    
containerize: #build-containerize
  dind: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.25@sha256:dd2000b525336acd00e9b95b74f15696797764725adbb25fa720e9431d558cbf
  script: |
    #!/usr/bin/env bash
    . $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/one-pipeline/scripts/package.sh
    exit $?

deploy:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.39@sha256:499559f10a289300828536196947da164c09cece319e3ce3f30fd408cde55c5d
  script: |
    #!/usr/bin/env bash
    . $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/one-pipeline/scripts/deploy.sh
    exit $?

acceptance-test:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.25@sha256:dd2000b525336acd00e9b95b74f15696797764725adbb25fa720e9431d558cbf
  script: |
    #!/usr/bin/env bash
    . $WORKSPACE/$PIPELINE_CONFIG_REPO_PATH/one-pipeline/scripts/acceptance-test.sh
    exit $?

release:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.39@sha256:499559f10a289300828536196947da164c09cece319e3ce3f30fd408cde55c5d
  script: |
    #!/usr/bin/env bash
    echo "Release Code goes here"
dynamic-scan:
  dind: true
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.25@sha256:dd2000b525336acd00e9b95b74f15696797764725adbb25fa720e9431d558cbf
  script: |
    #!/usr/bin/env bash
    echo "dynamic-scan Code goes here"
owasp-zap:
  dind: true
  abort_on_failure: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.25@sha256:dd2000b525336acd00e9b95b74f15696797764725adbb25fa720e9431d558cbf
  script: |
    #!/usr/bin/env bash
    echo "owasp-zap Code goes here"